baseURL = "http://rizaldi.id/"
languageCode = "en-us"
title = "Rizaldi Martaputra"
theme = "bootstrap"

paginate = 5
paginatePath = "page"

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  # Main sections (currently used for the recent posts in the sidebar)
  mainSections = ["post"]

  # Default author
  author = "Rizaldi M"
